version: "2"

networks:
  hackchange-net:
    driver: bridge

services:
  jupyter:
    image: diipushk/hackchange-notebook
    ports:
      - "10000:8888"
      - "4040:4040"
    volumes:
      - "${PWD}:/home/jovyan/work"
    environment:
    - JUPYTER_ENABLE_LAB=yes
    - GRANT_SUDO=yes
    - user=root
    networks:
      - hackchange-net

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/Users/diipushk/Documents/hackchange/hackchange/data/zookeeper_data"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - hackchange-net

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/Users/diipushk/Documents/hackchange/hackchange/data/kafka_data"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper
    networks:
      - hackchange-net

  aerospikedb:
      image: docker.io/aerospike/aerospike-server:latest
      ports:
      - "3000-3002:3000-3002"
      networks:
        - hackchange-net
      volumes:
      - "${PWD}/data/aerospike_data:/opt/aerospike/etc"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
