version: "2"

networks:
  hackchange-net:
    driver: bridge

services:
  jupyter:
    image: docker.io/jupyter/pyspark-notebook
    ports:
      - "10000:8888"
    volumes:
      - "${PWD}:/home/jovyan/work"
    environment:
    - JUPYTER_ENABLE_LAB=yes
    networks:
      - hackchange-net

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/Users/diipushk/Documents/hackchange/hackchange/data/zookeeper_data"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - hackchange-net

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/Users/diipushk/Documents/hackchange/hackchange/data/kafka_data"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper
    networks:
      - hackchange-net

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
